# Generated by Django 5.1.5 on 2025-01-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='categoria',
            field=models.CharField(choices=[('Cereais', 'Cereais'), ('Geleias', 'Geleias'), ('Frios', 'Frios'), ('Massas', 'Massas'), ('Bebidas', 'Bebidas')], max_length=100),
        ),
    ]
